name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Coursier cache
      #   uses: coursier/cache-action@v6
      - name: Setup
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      # - run: sbt compile
      # - run: sbt test
      - run: ./build.sh
