name: CI
on: push

jobs:
  # Label of the container job
  test:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:12-buster
    env:
      # The hostname used to communicate with the PostgreSQL service container
      CODEGEN_DB_HOST: postgres
      # The default PostgreSQL port
      CODEGEN_DB_PORT: 5432
      CODEGEN_DB_USER: codegenuser
      CODEGEN_DB_PASSWORD: postgres
      CODEGEN_DB_NAME: codegendb

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:12
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: codegenuser
          POSTGRES_DB: codegendb
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
#         ports:
#           - 5435:5432

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2
#       - name: Coursier cache
#         uses: coursier/cache-action@v6
      - name: Cache SBT
        uses: actions/cache@v2
        id: cache-sbt-dependencies
        with:
          path: |
            ~/.cache
            ~/.m2
            ~/.ivy2
            ~/.sbt
          key: ${{ runner.os }}-sbt2-${{ hashFiles('**/build.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt2-
      - name: Setup
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
#       - name: Install docker
#         run: | 
#           curl -fsSL https://get.docker.com -o get-docker.sh
#           sh get-docker.sh
#          docker login -p "${{ secrets.DOCKER_LOGIN_PASSWORD }}" -u rohansircar
#       - name: Migrate
#         run: csbt flyway/flywayMigrate
      - name: Run Tests
        run: |
          rm -rf "$HOME/.ivy2/local" || true
          find $HOME/Library/Caches/Coursier/v1        -name "ivydata-*.properties" -delete || true
          find $HOME/.ivy2/cache                       -name "ivydata-*.properties" -delete || true
          find $HOME/.cache/coursier/v1                -name "ivydata-*.properties" -delete || true
          find $HOME/.sbt                              -name "*.lock"               -delete || true
          csbt flyway/flywayMigrate
          csbt test
#       - name: Package
#         run: csbt docker:publish
