name: CI
on: push

jobs:
  # Label of the container job
  test:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
#    container: node:12-buster
#       volumes:
#           - ~/.sbt:~/.sbt
#           - ~/.ivy2/cache:~/.ivy2/cache
#           - ~/.coursier/cache/v1:~/.coursier/cache/v1
#           - ~/.cache/coursier/v1:~/.cache/coursier/v1
    env:
      # The hostname used to communicate with the PostgreSQL service container
      CODEGEN_DB_HOST: localhost
      # The default PostgreSQL port
      CODEGEN_DB_PORT: 5432
      CODEGEN_DB_USER: codegenuser
      CODEGEN_DB_PASSWORD: postgres
      CODEGEN_DB_NAME: codegendb

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:12
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: codegenuser
          POSTGRES_DB: codegendb
        # Set health checks to wait until postgres has started
        
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2
      #- name: Coursier cache
      #  uses: coursier/cache-action@v6
#       - name: Cache SBT
#         uses: actions/cache@v2
#         id: cache-sbt-dependencies
#         with:
#           path: |
#             $HOME/.sbt
#             $HOME/.ivy2/cache
#             $HOME/.coursier/cache/v1
#             $HOME/.cache/coursier/v1
#           key: ${{ runner.os }}-sbtnew-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
#           restore-keys: |
#             ${{ runner.os }}-sbtnew-
      - name: Setup
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
#       - name: Install docker
#         run: | 
#           curl -fsSL https://get.docker.com -o get-docker.sh
#           sh get-docker.sh
#          docker login -p "${{ secrets.DOCKER_LOGIN_PASSWORD }}" -u rohansircar
#       - name: Migrate
#         run: csbt flyway/flywayMigrate
      - name: Compile
        run: |
          echo "$HOME/.sbt" >> $GITHUB_PATH
          echo "$HOME/.cache/coursier/v1" >> $GITHUB_PATH
          echo "$HOME/.coursier/cache/v1" >> $GITHUB_PATH
          echo "$HOME/.ivy2/cache" >> $GITHUB_PATH
          csbt flyway/flywayMigrate
          csbt compile
          csbt test:compile
          DIR="$HOME/.sbt"
          if [ -d "$DIR" ]; then
            echo "Showing ${DIR}..."
            ls -lh "$DIR"
          else
            echo "Error: ${DIR} not found."
          
          fi

          DIR="$HOME/.cache/coursier/v1/https/repo1.maven.org/maven2/"
          if [ -d "$DIR" ]; then
            echo "Showing ${DIR}..."
            ls -lh "$DIR"
          else
            echo "Error: ${DIR} not found. "
            
          fi

          DIR="$HOME/.coursier"
          if [ -d "$DIR" ]; then
            echo "Showing ${DIR}..."
            ls -lh "$DIR"
          else
            echo "Error: ${DIR} not found."
            
          fi

          DIR="$HOME/.ivy2/cache"
          if [ -d "$DIR" ]; then
            echo "Showing ${DIR}..."
            ls -lh "$DIR"
          else
            echo "Error: ${DIR} not found. "
           
          fi
      - name: Run Tests
        run: |
          ls -alh ~/
#         csbt test
#       - name: Package
#         run: csbt docker:publish
